ignore:
  - "*/python?.?/*"
  - "*/migrations/*"
  - "*tests*"
  - "*manage*"
  - "*apps.py*"
  - "*production.py*"
  - "*staging.py*"
  - "*admin*"
  - "*__init__*"
  - "*migrations*"
  - "*/settings/.*"
  - "*urls.py*"
  - "*Procfile*"
  - "*db.sqlite*"